package com.cobarx.pubnetchk

import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Parses the committed sample report — generated by
 * `cargo run -p pubnet-tools --example sample_report -- --json` — and asserts the
 * `@Serializable` model reads the fields the skeleton UI shows. This is the
 * schema contract between the Rust `serde` output and the Kotlin side.
 */
class ReportParserTest {

    private fun sampleJson(): String =
        javaClass.classLoader!!.getResourceAsStream("sample-report.json")!!
            .bufferedReader().use { it.readText() }

    @Test
    fun parsesTheSampleReport() {
        val report = ReportJson.decoder.decodeFromString(Report.serializer(), sampleJson())

        assertEquals("0.1.0", report.version)
        assertEquals("High", report.score.level)
        assertEquals(40, report.score.total)
    }

    @Test
    fun readsTopologyFacts() {
        val t = ReportJson.decoder.decodeFromString(Report.serializer(), sampleJson()).topology
        assertEquals("ok", t.status)
        assertNotNull(t.data)
        assertEquals("wlan0", t.data!!.iface) // JSON key is `interface`
        assertEquals("wifi", t.data!!.interfaceKind)
        assertEquals("10.5.12.83/24", t.data!!.ipCidr)
        assertEquals("10.5.12.1", t.data!!.gateway)
        assertEquals(1, t.data!!.neighbors.size)
        assertTrue(t.data!!.neighbors.first().isGateway)
    }

    @Test
    fun readsSecurityFacts() {
        val s = ReportJson.decoder.decodeFromString(Report.serializer(), sampleJson()).security
        assertEquals("ok", s.status)
        val data = requireNotNull(s.data)
        assertEquals("Airport_Free_WiFi", data.ssid)
        assertEquals("Open", data.encryption)
        assertEquals("clean", data.dnsLeak?.verdict)
        assertFalse(data.captivePortal?.detected ?: true)
    }

    @Test
    fun readsScoreFindings() {
        val report = ReportJson.decoder.decodeFromString(Report.serializer(), sampleJson())
        val open = report.score.findings.firstOrNull { it.id == "security.wifi-open" }
        assertNotNull(open)
        assertEquals("alert", open!!.severity)
        assertEquals(40, open.points)
    }

    @Test
    fun toleratesUnknownFields() {
        // A new report field must not break an older app build.
        val withExtra = sampleJson().replaceFirst(
            "\"version\": \"0.1.0\"",
            "\"version\": \"0.1.0\", \"brandNewField\": {\"nested\": true}",
        )
        val report = ReportJson.decoder.decodeFromString(Report.serializer(), withExtra)
        assertEquals("0.1.0", report.version)
    }

    @Test
    fun buildsHostSnapshotJsonInCamelCase() {
        val snapshot = HostSnapshot(
            defaultRoute = SnapshotRoute("192.168.1.1", "wlan0"),
            interfaceAddr = SnapshotAddr("192.168.1.34", 24),
            arpNeighbors = listOf(SnapshotNeighbor("192.168.1.1", "a4:2b:b0:11:22:33", isGateway = true)),
            wifi = SnapshotWifi(ssid = "CoffeeWiFi", encryption = "WPA2", channel = 6, frequencyMhz = 2437),
            dns = SnapshotDns(servers = listOf("192.168.1.1"), currentServer = "192.168.1.1"),
            interfaceKind = "wifi",
        )
        val json = NetworkFacts.toJson(snapshot)
        assertTrue(json.contains("\"defaultRoute\""))
        assertTrue(json.contains("\"interfaceAddr\""))
        assertTrue(json.contains("\"isGateway\":true"))
        assertTrue(json.contains("\"frequencyMhz\":2437"))
        assertTrue(json.contains("\"interfaceKind\":\"wifi\""))
    }
}
